import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id "java-library"
}

// minestom requires java 21+
//sourceCompatibility = 25
//targetCompatibility = 25

repositories {
    mavenCentral()
}

dependencies {
    var minestom = "net.minestom:minestom:2026.05.17b-26.1.1"

    api(project(":common")) {
        // exclude default config providers as they are inaccessible from the minestom module anyway
        exclude group: "org.spongepowered", module: "configurate-yaml"
        exclude group: "org.spongepowered", module: "configurate-gson"
        exclude group: "org.spongepowered", module: "configurate-hocon"
        exclude group: "me.lucko.configurate", module: "configurate-toml"
    }
    api("org.slf4j:slf4j-api:2.0.17")
    compileOnly minestom

    // testing
    testImplementation(project(":common")) {
        // exclude default configurate dependency as it is wildly outdated
        exclude group: "org.spongepowered", module: "configurate-core"
    }
    testImplementation minestom
    testImplementation "commons-net:commons-net:3.11.1" // fix vulnerability in minestom
    testImplementation "ch.qos.logback:logback-classic:1.5.18" // logger

    // modern configurate
    testImplementation "org.spongepowered:configurate-core:4.2.0"
    testImplementation "org.spongepowered:configurate-hocon:4.2.0"

    // testing
    testImplementation "com.zaxxer:HikariCP:6.3.0"
    testImplementation "redis.clients:jedis:5.2.0"
    testImplementation "org.mariadb.jdbc:mariadb-java-client:3.5.3"
    testImplementation 'com.h2database:h2:2.1.214'
}

task processSource(type: Sync) {
    from sourceSets.main.java
    filter(ReplaceTokens, tokens: [VERSION: project.ext.fullVersion])
    into project.getLayout().getBuildDirectory().get().dir("src")
}

//license.ignoreFailures = true

compileJava {
    source = processSource.outputs
}

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {
    repositories {
        maven {
            name = 'hyperaSnapshots'
            url = 'https://repo.hypera.dev/snapshots/'
            credentials(PasswordCredentials)
        }
    }

    publications {
        mavenJava(MavenPublication) {
            artifactId = 'luckperms-minestom'

            from components.java

            pom {
                name = 'LuckPerms Minestom'
                description = 'A permissions plugin for Minestom servers.'
                url = 'https://github.com/LooFifteen/LuckPerms'

                licenses {
                    license {
                        name = 'MIT'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'lucko'
                        name = 'Luck'
                        url = 'https://lucko.me'
                        email = 'git@lucko.me'
                    }
                    developer {
                        id = 'LooFifteen'
                        name = 'LU15'
                        url = 'https://lu15.dev'
                        email = 'luis@lu15.dev'
                    }
                }

                scm {
                    connection = 'scm:git:https://github.com/LooFifteen/LuckPerms.git'
                    developerConnection = 'scm:git:git@github.com:LooFifteen/LuckPerms.git'
                    url = 'https://github.com/LooFifteen/LuckPerms'
                }

                issueManagement {
                    system = 'GitHub'
                    url = 'https://github.com/LooFifteen/LuckPerms/issues'
                }
            }
        }
    }
}
